### ISSUE TITLE
AndroidX migration

### ISSUE THREAD

**Issue by ghost** [jingliancui/XamarinFormsChatKitSample#1]
Hello!
I'm trying to make Xamarin Bindings for ChatKit library.
I want to migrate and compile it on my own computer.

I found your work at NuGet.org
Unfortunately your repository https://github.com/jingliancui/XamarinAndroidChatKit is down.

Could you please bring it up or share your Metadata.xml file?
It would really help me in my project.

Thanks for your time.

**Comment by jingliancui** [comment]
Hi @Enter25565 , I had been update the sample app to Forms 5.0 (AndroidX support), It's run without any problem.You can try it.

**Comment by ghost** [comment]
Thanks for reply. Unfortunately I use Xamarin.Android instead of Xamarin.Forms. ChatKitBinding.dll references old Support v7 instead of AndroidX. It should work, but I need to completely get rid of old Support libraries. Your Transforms\Metadata.xml could save me a lot of work.

**Comment by ghost** [comment]
Hi! Are you there?

**Comment by jingliancui** [comment]
Yep, I will take some time to have a look.

**Comment by jingliancui** [comment]
@Enter25565 It's seem like ChatKit still not compact with AndroidX, Please track this PR:
https://github.com/stfalcon-studio/ChatKit/pull/338

**Comment by ghost** [comment]
I agree! I migrated Java ChatKit to AndroidX on my own computer. Now I need to make Xamarin Bindings of that migrated version. But it shows build errors in Visual Studio. I don't want to start from scratch with adjusting Metadata.xml. Maybe I could provide you my AAR output from Android Studio or you could bring this up: https://github.com/jingliancui/XamarinAndroidChatKit (I get HTTP 404 error)

**Comment by jingliancui** [comment]
Yep,Could you provide the aar file here?

**Comment by jingliancui** [comment]
Done,
Just use this nuget:
Install-Package XamarinLibrary.Xamarin.AndroidX.ChatKit -Version 0.3.3
